import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

const repositoryRoot = resolve(import.meta.dirname, "../../..");

describe("public package CI source and artifact governance", () => {
  it("classifies S/A/C fail-closed and builds only detached source S", async () => {
    const workflow = await readFile(resolve(repositoryRoot, ".github/workflows/ci.yml"), "utf8");
    const classifier = workflow.match(/  public-package-head:[\s\S]*?(?=\n  checks:)/u)?.[0] ?? "";
    const checks = workflow.match(/  checks:[\s\S]*?(?=\n  public-package-producer:)/u)?.[0] ?? "";
    const producer = workflow.match(/  public-package-producer:[\s\S]*?(?=\n  public-package-consumer:)/u)?.[0] ?? "";
    const consumer = workflow.match(/  public-package-consumer:[\s\S]*?(?=\n  [a-z][a-z-]+:|$)/u)?.[0] ?? "";
    const generatedCustody = workflow.match(/  public-package-generated-custody:[\s\S]*?(?=\n  [a-z][a-z-]+:|$)/u)?.[0] ?? "";
    expect(classifier).toContain("github.event.pull_request.head.sha || github.sha");
    expect(classifier).toContain("fetch-depth: 0");
    expect(classifier).toContain("public-package-head-governance.mjs");
    expect(checks).toContain("needs: [public-package-head, public-package-generated-custody]");
    expect(checks).toContain("always() &&");
    expect(checks).toContain("needs.public-package-head.result == 'success'");
    expect(checks).toContain("needs.public-package-head.outputs.kind == 'source'");
    expect(checks).toContain("needs.public-package-generated-custody.result == 'success'");
    expect(classifier).toContain("$GITHUB_OUTPUT");
    expect(checks).toContain("github.event.pull_request.head.sha || github.sha");
    expect(checks).toMatch(/if: needs\.public-package-head\.outputs\.kind == 'generated'[\s\S]*?public-package-head-governance\.mjs/u);
    expect(checks).toMatch(/if: needs\.public-package-head\.outputs\.kind == 'source'[\s\S]*?npm run build:public/u);
    expect(producer).toContain("needs: [checks, public-package-head]");
    expect(producer).toContain("if: needs.public-package-head.outputs.kind == 'source'");
    expect(producer).toContain("ref: ${{ needs.public-package-head.outputs.source-head }}");
    expect(producer).toContain("git symbolic-ref -q HEAD");
    expect(producer).toContain('test "$GITHUB_RUN_ATTEMPT" = "1"');
    expect(producer).toContain("start a new workflow run");
    expect(producer).toContain("compare-public-package-trees.mjs");
    expect(producer.match(/archive: false/gu)).toHaveLength(2);
    expect(producer.match(/if-no-files-found: error/gu)).toHaveLength(2);
    expect(producer.match(/overwrite: false/gu)).toHaveLength(2);
    expect(consumer).toContain("artifact-ids:");
    expect(consumer).not.toMatch(/\n\s+name:\s+public-package/u);
    expect(consumer).toContain("^[1-9][0-9]*$");
    expect(consumer).toContain("sha256sum");
    expect(consumer).toContain("--tarball");
    expect(consumer).toContain("--receipt");
    expect(consumer).toContain("github-token: ${{ github.token }}");
    expect(consumer).toContain("repository: ${{ github.repository }}");
    expect(consumer).toContain("run-id: ${{ github.run_id }}");
    expect(consumer.match(/skip-decompress: true/gu)).toHaveLength(2);
    expect(consumer.match(/digest-mismatch: error/gu)).toHaveLength(2);
    expect(generatedCustody).toContain("needs: public-package-head");
    expect(generatedCustody).not.toContain("needs: [checks");
    expect(generatedCustody).toContain("needs.public-package-head.outputs.kind == 'generated'");
    expect(generatedCustody).toContain("public-package-ci-custody-intake.mjs");
    expect(generatedCustody).toContain("verify-public-package-ci-custody-github.mjs");
    expect(generatedCustody).toContain("gh api --method GET");
    expect(generatedCustody).toContain("/actions/runs/");
    expect(generatedCustody).toContain("/actions/artifacts/");
    expect(generatedCustody).not.toContain("artifact-name:");
    expect(generatedCustody).not.toMatch(/actions\/artifacts\?name=|\/runs\/latest/iu);
    expect(generatedCustody.match(/artifact-ids:/gu)).toHaveLength(2);
    expect(generatedCustody.match(/run-id:/gu)).toHaveLength(2);
    expect(generatedCustody.match(/skip-decompress: true/gu)).toHaveLength(2);
    expect(generatedCustody.match(/digest-mismatch: error/gu)).toHaveLength(2);
    expect(generatedCustody).toContain("cmp --silent");
  });
});
